"""
Pydantic models for migration operations
"""

from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any
from enum import Enum
from datetime import datetime


class MigrationStep(str, Enum):
    """Migration step types"""
    STEP_1_NON_CDB_TO_PDB = "step_1_non_cdb_to_pdb"
    STEP_2_PDB_19C_TO_23C = "step_2_pdb_19c_to_23c"


class MigrationStatus(str, Enum):
    """Migration status"""
    PENDING = "pending"
    ANALYZING = "analyzing"
    PLANNING = "planning"
    AWAITING_APPROVAL = "awaiting_approval"
    APPROVED = "approved"
    EXECUTING = "executing"
    VALIDATING = "validating"
    COMPLETED = "completed"
    FAILED = "failed"
    ROLLED_BACK = "rolled_back"
    CANCELLED = "cancelled"


class MigrationPriority(str, Enum):
    """Migration wave priority"""
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class DatabaseType(str, Enum):
    """Database type"""
    ORACLE_19C_STANDALONE = "oracle_19c_standalone"
    ORACLE_19C_CDB_PDB = "oracle_19c_cdb_pdb"
    ORACLE_23C_CDB_PDB = "oracle_23c_cdb_pdb"


class DatabaseConfig(BaseModel):
    """Database configuration"""
    db_id: str = Field(..., description="Unique database identifier")
    db_type: DatabaseType
    host: str
    port: int
    service_name: str
    username: str
    password: str = Field(..., description="Encrypted in production")
    pdb_name: Optional[str] = None


class TableInfo(BaseModel):
    """Table information"""
    table_name: str
    schema_name: str
    row_count: int
    size_mb: float
    selected: bool = True


class MigrationRequest(BaseModel):
    """Migration request"""
    migration_name: str = Field(..., description="Human-readable migration name")
    source_db: DatabaseConfig
    intermediate_db: Optional[DatabaseConfig] = None
    target_db: DatabaseConfig
    tables: List[TableInfo]
    migration_mode: str = Field(default="two_step", description="Migration mode: two_step or direct")
    business_priority: MigrationPriority = MigrationPriority.MEDIUM
    max_downtime_minutes: Optional[int] = Field(default=60, description="Maximum acceptable downtime")
    user_notes: Optional[str] = None


class DependencyInfo(BaseModel):
    """Dependency information"""
    table_name: str
    depends_on: List[str]
    dependency_type: str  # foreign_key, view, trigger, etc.
    risk_level: str  # low, medium, high


class MigrationPlan(BaseModel):
    """Migration plan generated by AI"""
    plan_id: str
    migration_id: str
    step: MigrationStep
    execution_order: List[str] = Field(..., description="Tables in execution order")
    dependencies: List[DependencyInfo]
    estimated_duration_minutes: int
    risk_assessment: str
    pre_checks: List[str]
    post_checks: List[str]
    rollback_strategy: str
    ai_reasoning: str = Field(..., description="AI agent's reasoning for the plan")
    requires_approval: bool = True
    created_at: datetime = Field(default_factory=datetime.utcnow)


class ValidationResult(BaseModel):
    """Validation result"""
    validation_id: str
    migration_id: str
    step: MigrationStep
    source_row_count: int
    target_row_count: int
    row_count_match: bool
    schema_match: bool
    constraint_match: bool
    index_match: bool
    issues: List[Dict[str, Any]] = []
    passed: bool
    validation_time: datetime = Field(default_factory=datetime.utcnow)


class AgentLog(BaseModel):
    """Agent reasoning log"""
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    agent_name: str
    action: str
    reasoning: str
    metadata: Dict[str, Any] = {}


class MigrationProgress(BaseModel):
    """Migration progress"""
    migration_id: str
    status: MigrationStatus
    current_step: Optional[MigrationStep]
    current_table: Optional[str]
    tables_completed: int
    tables_total: int
    progress_percentage: float
    started_at: Optional[datetime]
    completed_at: Optional[datetime]
    agent_logs: List[AgentLog] = []
    error_message: Optional[str] = None


class MigrationResponse(BaseModel):
    """Migration response"""
    migration_id: str
    status: MigrationStatus
    message: str
    plan: Optional[MigrationPlan] = None
    progress: Optional[MigrationProgress] = None


class ApprovalRequest(BaseModel):
    """Approval request"""
    migration_id: str
    approved: bool
    comments: Optional[str] = None
    approver: str


class SchemaAnalysis(BaseModel):
    """Schema analysis result"""
    db_id: str
    total_tables: int
    total_size_mb: float
    tables: List[TableInfo]
    dependencies: List[DependencyInfo]
    compatibility_issues: List[str] = []
    readiness_score: float = Field(..., ge=0, le=100, description="0-100 readiness score")
    analysis_time: datetime = Field(default_factory=datetime.utcnow)
