ALTER SESSION SET CONTAINER = XEPDB1;
CREATE USER migration_user IDENTIFIED BY MigrationPwd123 DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP QUOTA UNLIMITED ON USERS;
GRANT CONNECT, RESOURCE, CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE, SELECT ANY TABLE, SELECT ANY DICTIONARY TO migration_user;
EXIT;
